// All the actions for Instaurant
const actionTypes = {
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    RECEIVE_CATEGORY: 'RECEIVE_CATEGORY',
    ADD_CATEGORY: 'ADD_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',

    FETCH_DISH: 'FETCH_DISH',
    RECEIVE_DISH: 'RECEIVE_DISH',
    ADD_DISH: 'ADD_DISH',
    UPDATE_DISH: 'UPDATE_DISH',
    DELETE_DISH: 'DELETE_DISH',
};

export default actionTypes;
